services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.vips
    environment:
      - ANNABELLE_VARIANT_PROCESSOR=vips
      - RAILS_ENV=test
      - DOCKER=1
    volumes:
      - ../:/app
    ports:
      - "3000:3000"
    # command: bash -c "bundle exec rails db:setup && bundle exec rspec ./spec/system/auth/account_settings_spec.rb:15"
    # command: bash -c "bundle exec rails db:reset && rails db:setup && bundle exec rspec spec/system/auth/account_settings_spec.rb:15"
    command: bash -c "bundle exec rails db:reset && rails db:setup && bundle exec rspec"
